@baseUrl = http://localhost:3000
@userToken = Bearer TOKEN
@adminToken = Bearer TOKEN

### =========================
### AUTH
### =========================

### Login (user / admin)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@local.dev",
  "password": "12345"
}

### =========================
### USERS (SELF)
### =========================

### Get all users
GET {{baseUrl}}/users
Authorization: {{userToken}}

### Get user by id
GET {{baseUrl}}/users/2
Authorization: {{adminToken}}

### Create user (public)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "userP@local.dev",
  "password": "12345",
  "profile": {
    "name": "Carlos"
  }
}

### Self update
PUT {{baseUrl}}/users/me
Authorization: {{userToken}}
Content-Type: application/json

{  
  "password": "probandotodo",
  "profile": {
    "name": "CarlosEdSelf",
    "avatar": "https://exampleSelf.com/avatar.png"
  }
}

### Self delete (soft delete)
DELETE {{baseUrl}}/users/me
Authorization: {{userToken}}

### =========================
### ADMIN – USERS
### =========================

### Admin update user
PUT {{baseUrl}}/admin/users/8
Authorization: {{adminToken}}
Content-Type: application/json

{
  "email": "userl@local.dev",
  "password": "probandotodo",
  "profile": {
    "name": "CarlosEd",
    "avatar": "https://example.com/avatar.png"
  },
  "systemRoleId": 2
}

### Admin delete user (soft delete)
DELETE {{baseUrl}}/admin/users/10
Authorization: {{adminToken}}

### Restore user (admin)
PUT {{baseUrl}}/admin/users/2/restore
Authorization: {{adminToken}}


### BOARDS
### Create board
POST {{baseUrl}}/boards
Authorization: {{userToken}}
Content-Type: application/json

{
  "name": "board de prueba2"
}

### Get all boards
GET {{baseUrl}}/boards
Authorization: {{userToken}}

### Get board by id
GET {{baseUrl}}/boards/7
Authorization: {{userToken}}

### Update board
PUT {{baseUrl}}/boards/70
Authorization: {{userToken}}
Content-Type: application/json

{
  "name": "board de pruebad",
  "ownerId": 40
}

### Soft delete board by id
DELETE {{baseUrl}}/boards/7
Authorization: {{userToken}}

### Restore board by id
PUT {{baseUrl}}/boards/7/restore
Authorization: {{userToken}}