@baseUrl = http://localhost:3000
@userToken = Bearer TOKEN
@adminToken = Bearer TOKEN

### =========================
### AUTH
### =========================

### Login (user / admin)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user3@local.dev",
  "password": "12345"
}

### =========================
### USERS (SELF)
### =========================

### Get all users (admin or authorized)
GET {{baseUrl}}/users
Authorization: {{adminToken}}

### Get user by id
GET {{baseUrl}}/users/1
Authorization: {{adminToken}}

### Create user (public)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "userN@local.dev",
  "password": "12345",
  "profile": {
    "name": "Carlos"
  }
}

### Self update
PUT {{baseUrl}}/users/me
Authorization: {{userToken}}
Content-Type: application/json

{
  "email": "user8@local.dev",
  "password": "probandotodo",
  "profile": {
    "name": "CarlosEdSelf",
    "avatar": "https://exampleSelf.com/avatar.png"
  }
}

### Self delete (soft delete)
DELETE {{baseUrl}}/users/me
Authorization: {{userToken}}

### =========================
### ADMIN – USERS
### =========================

### Admin update user
PUT {{baseUrl}}/admin/users/8
Authorization: {{adminToken}}
Content-Type: application/json

{
  "email": "userl@local.dev",
  "password": "probandotodo",
  "profile": {
    "name": "CarlosEd",
    "avatar": "https://example.com/avatar.png"
  },
  "systemRoleId": 2
}

### Admin delete user (soft delete)
DELETE {{baseUrl}}/admin/users/5
Authorization: {{adminToken}}

### Restore user (admin)
PUT {{baseUrl}}/admin/users/12/restore
Authorization: {{adminToken}}
